import { GoogleGenAI, Type, Chat } from "@google/genai";
import { Issue, Persona, AuditConfig } from '../types';

// Initialize Gemini Client
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

const SYSTEM_INSTRUCTION = `
You are A11y-Agent, an elite web accessibility expert and software engineer. 
Your mission is to audit web interfaces for accessibility issues based on WCAG 2.1 AA/AAA standards.
You will simulate the experience of users with specific disabilities (Visual, Motor, Color Blindness).
You provide actionable, code-level fixes using modern best practices (semantic HTML, ARIA, focus management).
Always be constructive, precise, and empathetic in your explanations.
`;

export const analyzeAccessibility = async (config: AuditConfig): Promise<Issue[]> => {
  const model = 'gemini-3-flash-preview';
  
  const prompts: any[] = [];
  
  // Base context
  let promptText = `Analyze the provided web page content (HTML and/or Screenshot) for accessibility issues. 
  Target URL: ${config.url}.
  Selected Personas to audit for: ${config.personas.join(', ')}.
  
  Return a raw JSON array of issue objects. Do not use Markdown formatting for the JSON. 
  Each object must strictly follow this schema:
  {
    "id": "unique_id",
    "title": "Short title of the issue",
    "description": "Clear explanation of the problem from the user's perspective",
    "severity": "CRITICAL" | "HIGH" | "MEDIUM" | "LOW",
    "persona": "VISUAL" | "MOTOR" | "COLOR",
    "element": "The HTML tag or element name involved (e.g., <button>)",
    "codeSnippet": "The problematic code",
    "suggestedFix": "The corrected code",
    "explanation": "Why this fix works (technical educational context)",
    "location": { "x": 50, "y": 50 } // Approximate percentage coordinates (0-100) on the visual viewport if applicable, or null.
  }
  
  Specific Guidelines:
  - For VISUAL persona (Screen Reader): Check for missing alt text, empty buttons, semantic structure (headings), ARIA misuse.
  - For COLOR persona: Check for low contrast text, color-only indicators.
  - For MOTOR persona: Check for keyboard traps, focus visibility, small touch targets.
  `;

  if (config.rawHtml) {
    promptText += `\n\nHTML SOURCE CODE:\n${config.rawHtml.substring(0, 30000)}... (truncated)`;
  }

  prompts.push({ text: promptText });

  // Add screenshot if available
  if (config.screenshotBase64) {
    prompts.push({
      inlineData: {
        mimeType: 'image/png',
        data: config.screenshotBase64.split(',')[1] // Remove data URL prefix
      }
    });
  }

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: { parts: prompts },
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        responseMimeType: "application/json",
        // We use a high token limit to allow detailed code fixes
        maxOutputTokens: 8192, 
      }
    });

    const text = response.text;
    if (!text) return [];
    
    // Clean up if the model adds markdown code blocks despite instructions
    const jsonStr = text.replace(/```json/g, '').replace(/```/g, '').trim();
    return JSON.parse(jsonStr) as Issue[];

  } catch (error) {
    console.error("Gemini Analysis Failed:", error);
    throw new Error("Failed to analyze the content. Please ensure your API Key is valid.");
  }
};

export const generateFixPullRequest = async (issues: Issue[], repoUrl: string) => {
  const prompt = `
  I have identified the following accessibility issues on ${repoUrl}:
  ${issues.map(i => `- [${i.severity}] ${i.title}: ${i.description}`).join('\n')}
  
  Draft a professional GitHub Pull Request description.
  Return the response in JSON format with two fields: "title" and "body".
  The body should include a summary of changes and the impact on users.
  `;

  const response = await ai.models.generateContent({
    model: 'gemini-3-flash-preview',
    contents: prompt,
    config: {
      responseMimeType: "application/json"
    }
  });

  return JSON.parse(response.text || '{}');
};

export const createChatSession = (initialContext?: string): Chat => {
  let systemInstruction = `You are the A11y-Agent AI Assistant. Your goal is to help users understand web accessibility and WCAG guidelines (Level A, AA, AAA). 
      
      Context about the app you are embedded in:
      - This is "A11y-Agent", an AI-powered accessibility auditing tool.
      - It audits websites for Visual, Motor, and Color Blindness accessibility issues.
      - It uses Gemini 3 to analyze HTML and screenshots.
      
      Your Role:
      - Answer questions about accessibility best practices.
      - Assist the user in understanding the audit reports generated by this app.
      - Be concise, professional, and encouraging.`;

  if (initialContext) {
    systemInstruction += `\n\nCURRENT AUDIT CONTEXT:\n${initialContext}`;
  }

  return ai.chats.create({
    model: 'gemini-3-pro-preview',
    config: {
      systemInstruction: systemInstruction,
    },
  });
};
